### PR TITLE
Fruxo upstream merge

### PR DESCRIPTION
**Pull request by Zomtir**
This is a full merge of current fruxo/master.

The multi touch API and code has changed, here's a list of what has been taken from each branch:
- Turbodager: Invoke and event syntax (e.g EVENT_TYPE_TOUCH_* rather than EVENT_TYPE_FINGER )
- Turbodager: Finger ID handling
- Hastybadger: Touch Gesture (aka MultiGesture)
- Hastybadger: Triggering Pointer and Touch events at the same time on touch (with touch boolean) rather than forwarding from Touch->Pointer for a single finger.

Each commit has been tested with "make sdl2" and an execution of the demo.

### CODE REVIEW

**Comment by Zomtir** [comment]
The touch API is not yet suited for touchpads because their movement cannot be mapped 1:1 onto the screen. I will have to change it to make touch input independent from the pointer location again.

**Comment by Xeverous** [comment]
Just a note: **this repo has not enabled issues**. It's virtually impossible to propose anything to the repo while the readme encourages doing so.

Commenting here (most recent PR) ... because I can not open an issue.

**Comment by tesch1** [comment]
Thanks for the note, they're enabled now.

**Comment by tesch1** [comment]
A note for outside observers - this PR is in limbo -- it contains a lot of changes and it's hard to test them all.  I see a few different things going on here 1) merging the fruxo/turbobadger mainline, 2) switching to a different(new) multi-touch / gesture model, 3) ?

I haven't had time to review all of these things, and some of them are changes to APIs that are in use elsewhere, so I wouldn't count on this being merged as-is.

**Comment by Zomtir** [comment]
> 2) switching to a different(new) multi-touch / gesture model

I'm trying so summarize the changes in ff533f4a59d7fdfd16dc896c2574a60d5bdbee81 and 0828da2ff587e457226db8aa9e272899811ad737

There were five trivial changes:
- FINGER_DOWN was renamed to TOUCH_DOWN (leaning on the upstream syntax by fruxo)
- Integer type change from uint32 to uint32_t
- Moved the InvokeWheel function
- Renamed NewTouchInfo to AddTouchInfo (this function is only used privately)
- Make use of IsTouchEvent() rather than testing for the cases individually
- Eearlier bails (returns false) for missing widgets. They no longer reach the end of the function and use less indention.

The remaining changes boil down to those three:
- The attributes from TBWidgetEventFinger were merged into TBWidgetEvent. The vast majority already had a corresponding counterpart. The only complete new attributes added to TBWidgetEvent were delta_theta and delta_dist.
- The constructors from TBWidgetEventFinger were added to TBWidgetEvent
- Renamed InvokeFingerMotion to InvokeTouchGesture. The only difference in the body consits of the TBWidgetEvent trigger rather than the superseded TBWidgetEventFinger.

All in all it's a very lightweight addition of a InvokeTouchGesture() method compared to the fruxo master branch.

> 3) ?

There were no additional changes beside the two commits mentioned above. All other commits (authored on fruxo master) can be compiled by their own and have only be minorly adapted to the current code base (~90% uint32 to uint32_t).

I hope this helps for the review.

**Pull request closed without merging**
